Carousel
hunterrudnet/rave pull request #2
Opened 2023-02-24 23:08 UTC by hadeel-farhan

Created the filter, search, card, and carousel components. I still need to be able to take in an object and make the test object be passed in because its all hardcoded.

2023-02-26 00:41 UTC, hunterrudnet requested changes
Was this the MUI version? I don't see any MUI in here and lots of it just seems ripped from another repository. Let's try to rework it so that the components are functional, and we can use Material-UI where applicable! Thanks

2023-02-26 00:41 UTC, hunterrudnet commented on package.json
> +    "react-scripts": "^2.1.3",
why the huge downgrade?

2023-02-26 00:41 UTC, hunterrudnet commented on src/carousel/card.html
> +    <!-- <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script> -->
what are these comments?

2023-02-26 00:41 UTC, hunterrudnet commented on src/carousel/card.js
> +export default class Card extends Component {
why class based React Components? We have been doing functional components in this class

2023-02-28 22:27 UTC, hadeel-farhan commented
Carousel from https://www.npmjs.com/package/react-spring-3d-carousel

2023-02-28 22:33 UTC, hunterrudnet requested changes

2023-02-28 22:33 UTC, hunterrudnet commented on src/components/Carousel/Cards.js
> +    render() {
can we please change this to functional?

2023-02-28 22:33 UTC, hunterrudnet commented on src/components/Carousel/Card.css
> +/* .css-1qzevvg {
can we remove this comment, and rename the class selector to something more readable?

2023-02-28 22:33 UTC, hunterrudnet commented on src/App.js
> +        {/* <LoginButton />
Minor, but let's uncomment these to make sure everything works, and add a route for your components to test the render

2023-03-01 13:34 UTC, closed without merging